# Generated by Django 3.2 on 2021-05-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
