# Generated by Django 3.2.2 on 2021-05-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(default='null', upload_to='post_img/'),
        ),
    ]
